version: '2'

services:
  app:
    build:
      context: .
    container_name: app
    restart: always
    ports:
      - 8089:8089
    depends_on:
      - db    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbi:5432/onlineflatrental
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Appa123@
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: dbi
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Appa123@
      - POSTGRES_DB=onlineflatrental
   
      
