version: '3.8'

services:
  app:
    build:
      context: .
    container_name: app
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db    
   # environment:
    #  - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/onlineflatrental
     # - SPRING_DATASOURCE_USERNAME=postgres
      #- SPRING_DATASOURCE_PASSWORD=Appa123@
     # - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: dbb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Appa123@
      - POSTGRES_DB=onlineflatrental
   
      